MetaDataFormat: yaml
baseurl: 'https://portuguesewomenintech.com'
blackfriday:
  hrefTargetBlank: true
title: PT Women in Tech
googleAnalytics: UA-46722009-2
taxonomies:
  tag: tags

# i18n
DefaultContentLanguage: "en"
DefaultContentLanguageInSubdir: true

# Params per language
Languages:
  en:
    locale: "en-us"
    description:  >-
      A portrait of the women that help make the difference in the portuguese tech
      industry.
