backend:
  name: github
  repo: porto-io/PWiT # Path to your Github repository
  branch: <% CURRENT_BRANCH %> # Branch to update (master by default)

media_folder: "/static/images/profiles" # Folder where user uploaded files should go
public_folder: "/images/profiles"

publish_mode: editorial_workflow

collections: # A list of collections the CMS should be able to edit
  - name: "profile" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Profiles" # Used in the UI, ie.: "New Post"
    folder: "content/profiles" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
      - label: "Profile picture"
        name: "image"
        widget: "image"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Time in Tech"
        name: "timeInTech"
        widget: "string"
      - label: "Subtitle / Current Role"
        name: "description"
        widget: "string"
      - label: "Place of Origin"
        name: "placeOfOrigin"
        widget: "string"
      - label: "Social Links"
        name: "socialLinks"
        widget: "list"
        fields:
          - label: "Social Network (twitter / linkedin / medium / facebook / instagram / website)"
            name: "name"
            widget: "select"
            options:
              - ""
              - "twitter"
              - "linkedin"
              - "medium"
              - "facebook"
              - "instagram"
              - "website"
          - label: "URL"
            name: "url"
            widget: "string"
      - label: "Body"
        name: "body"
        widget: "markdown"
      - label: "Profile Tags (tag1, tag2, tag3)"
        name: "tags"
        widget: list

  - name: "partners" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Partners" # Used in the UI, ie.: "New Post"
    folder: "content/partners" # The path to the folder where the documents are stored
    create: false # Allow users to create new documents in this collection
    fields:
      - label: "Title"
        name: "title"
        widget: "hidden"
      - label: "Partner Tier"
        name: "partner_tier"
        widget: "list"
        fields:
          - label: "Name"
            name: "title"
            widget: "string"
          - label: "Logos"
            name: "logos"
            widget: "list"
            fields:
              - label: "Partner Name"
                name: "name"
                widget: "string"
              - label: "Image"
                name: "image"
                widget: "image"
              - label: "URL"
                name: "link"
                widget: "string"

  - name: "settings"
    label: "Settings"
    files:
      - label: "Site settings"
        name: "general"
        file: "config.yml"
        fields:
          - label: "Site title"
            name: "title"
            description: "The website's title, used for page titles"
            widget: "string"
          - label: "Google Analytics code"
            name: "googleAnalytics"
            description: "Google Analytics site identifier (UA-XXXXXXXX-X)"
            widget: "string"
